// alert("Array is loaded");
var colors = ["red", "blue", "green"];
console.log(colors);
console.log(typeof(colors));
console.log(colors[1]);
colors.push('orange');
console.log(colors);
colors.pop();
console.log(colors);
colors.shift();
console.log(colors);
colors.unshift("yellow");
console.log(colors);
colors[1] = "blue2";
console.log(colors);
var colors2 = ["purple", "orange", "pink"];
console.log(colors.concat(colors2));
colors = colors.concat(colors2);
console.log(colors);
